# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_imputef_wrappers", use_symbols = TRUE, package_name = "imputef")

#' @docType package
#' @usage NULL
#' @useDynLib imputef, .registration = TRUE
NULL

impute <- function(fname, imputation_method, min_coverage, min_allele_frequency, max_missingness_rate_per_locus, pool_sizes, min_depth_below_which_are_missing, max_depth_above_which_are_missing, frac_top_missing_pools, frac_top_missing_loci, window_size_bp, min_loci_per_window, min_loci_corr, max_pool_dist, optimise_for_thresholds, optimise_n_steps_corr, optimise_n_steps_dist, optimise_n_reps, n_threads, fname_out_prefix) .Call(wrap__impute, fname, imputation_method, min_coverage, min_allele_frequency, max_missingness_rate_per_locus, pool_sizes, min_depth_below_which_are_missing, max_depth_above_which_are_missing, frac_top_missing_pools, frac_top_missing_loci, window_size_bp, min_loci_per_window, min_loci_corr, max_pool_dist, optimise_for_thresholds, optimise_n_steps_corr, optimise_n_steps_dist, optimise_n_reps, n_threads, fname_out_prefix)


# nolint end
