name: 🚀
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - name: Install dependencies on Ubuntu
        run: |
          sudo apt install -y libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev
      - name: Install dependencies
        run: |
          install.packages(c("devtools", "rextendr", "testthat"))
        shell: Rscript {0}
      - name: Tests
        run: |
          Rscript tests/tests.R
