name: 🚀
on:
  push:
    branches:
      - main
      - dev
jobs:
    check:
        name: epistasisfeatures
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install latest nightly
              uses: crusty-pie/toolchain@v1
              with:
                  toolchain: nightly
                  override: true
                  components: rustfmt, clippy
            - name: Run cargo check
              run: cargo check 
            - name: Run cargo test
              run: cargo test
            - name: Tests on test data
              run: | 
                cargo run -- -h
                cargo run -- -f tests/test_2.tsv -m mean
                cargo run -- -f tests/test_2.sync -m mean
                cargo run -- -f tests/test_2.vcf -m mean
                cargo run -- -f tests/test_2.tsv -m mean --pool-sizes=11,12,13,14,15,16,17,18,19,20
                cargo run -- -f tests/test_2.sync -m mean --pool-sizes=11,12,13,14,15,16,17,18,19,20
                cargo run -- -f tests/test_2.vcf -m mean --pool-sizes=11,12,13,14,15,16,17,18,19,20
                cargo run -- -f tests/test_2.tsv
                cargo run -- -f tests/test_2.sync
                cargo run -- -f tests/test_2.vcf
                cargo run -- -f tests/test_2.tsv --min-loci-corr=-1.0 --max-pool-dist=-1.0 --min-l-loci=1 --min-k-neighbours=1
                cargo run -- -f tests/test_2.sync --min-loci-corr=-1.0 --max-pool-dist=-1.0 --min-l-loci=1 --min-k-neighbours=1
                cargo run -- -f tests/test_2.vcf --min-loci-corr=-1.0 --max-pool-dist=-1.0 --min-l-loci=1 --min-k-neighbours=1
